--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-24-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence TMP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PBJ2577"."TMP_SEQ"  MINVALUE 1 MAXVALUE 1000 INCREMENT BY 1 START WITH 12 NOCACHE  NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "C##PBJ2577"."ACCOUNTS" 
   (	"SEQ" NUMBER(*,0), 
	"ID" VARCHAR2(30 BYTE), 
	"PW" VARCHAR2(50 BYTE), 
	"SEX" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##PBJ2577"."ACCOUNTS"."PW" IS 'encryption';
   COMMENT ON COLUMN "C##PBJ2577"."ACCOUNTS"."SEX" IS 'male/female
';
REM INSERTING into C##PBJ2577.ACCOUNTS
SET DEFINE OFF;
Insert into C##PBJ2577.ACCOUNTS (SEQ,ID,PW,SEX) values (9,'id4','pw2','info');
Insert into C##PBJ2577.ACCOUNTS (SEQ,ID,PW,SEX) values (4,'id4','pw2','info');
Insert into C##PBJ2577.ACCOUNTS (SEQ,ID,PW,SEX) values (6,'id4','pw2','info');
Insert into C##PBJ2577.ACCOUNTS (SEQ,ID,PW,SEX) values (7,'id4','pw2','info');
Insert into C##PBJ2577.ACCOUNTS (SEQ,ID,PW,SEX) values (8,'id4','pw2','info');
Insert into C##PBJ2577.ACCOUNTS (SEQ,ID,PW,SEX) values (1,'id1','pw2','info');
Insert into C##PBJ2577.ACCOUNTS (SEQ,ID,PW,SEX) values (2,'id2','pw2','info');
Insert into C##PBJ2577.ACCOUNTS (SEQ,ID,PW,SEX) values (3,'id2','pw2','info');
Insert into C##PBJ2577.ACCOUNTS (SEQ,ID,PW,SEX) values (5,'id2','pw2','info');
Insert into C##PBJ2577.ACCOUNTS (SEQ,ID,PW,SEX) values (10,'id4','pw2','info');
Insert into C##PBJ2577.ACCOUNTS (SEQ,ID,PW,SEX) values (11,'id4','pw2','info');
--------------------------------------------------------
--  DDL for Index ACCOUNTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PBJ2577"."ACCOUNTS_PK" ON "C##PBJ2577"."ACCOUNTS" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACCOUNTS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PBJ2577"."ACCOUNTS_UK1" ON "C##PBJ2577"."ACCOUNTS" ("ID", "SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "C##PBJ2577"."ACCOUNTS" MODIFY ("SEQ" NOT NULL ENABLE);
  ALTER TABLE "C##PBJ2577"."ACCOUNTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##PBJ2577"."ACCOUNTS" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "C##PBJ2577"."ACCOUNTS" MODIFY ("SEX" NOT NULL ENABLE);
  ALTER TABLE "C##PBJ2577"."ACCOUNTS" ADD CONSTRAINT "ACCOUNTS_PK" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PBJ2577"."ACCOUNTS" ADD CONSTRAINT "ACCOUNTS_UK1" UNIQUE ("ID", "SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
